SELECT B.TABLE_NAME
,A.COLUMN_NAME
,B.NUM_ROWS
,A.NUM_DISTINCT
,A.NUM_NULLS
,B.AVG_ROW_LEN
,A.AVG_COL_LEN
,A.DATA_TYPE

FROM ALL_TAB_COLUMNS A
INNER JOIN ALL_TABLES B ON A.TABLE_NAME = B.TABLE_NAME AND A.OWNER = B.OWNER